<?php
	$page=(isset($_GET['page']))? $_GET['page']: "index";
	switch ($page) {
	case 'data_keluhan': include 'user/data_keluhan.php';
	break;
	case 'search_keluhan': include 'user/search_keluhan.php';
	break;
	case 'data_komentar': include 'user/data_komentar.php';
	break;
	case 'search_komentar': include 'user/search_komentar.php';
	break;
	case 'guestbook': include 'pages/guestbook.php';
	break;
	case 'bkk': include 'pages/bkk.php';
	break;
	case 'developer': include 'pages/developer.php';
	break;
	case 'contact': include 'pages/contact.php';
	break;
	case 'gallery': include 'pages/gallery.php';
	break;
	case 'login': include 'pages/login.php';
	break;
	case 'prestasi': include 'pages/prestasi.php';
	break;
	case 'profil': include 'pages/profil.php';
	break;
	case 'titl': include 'pages/titl.php';
	break;
	case 'tkr': include 'pages/tkr.php';
	break;
	case 'pbo': include 'pages/pbo.php';
	break;
	case 'tp': include 'pages/tp.php';
	break;
	case 'rpl': include 'pages/rpl.php';
	break;
	case 'factory': include 'pages/factory.php';
	break;
	case 'data_kelas': include 'pages/data_kelas.php';
	break;
	case 'add_kelas': include 'pages/add_kelas.php';
	break;
	case 'edit_kelas': include 'pages/edit_kelas.php';
	break;
	case 'search_kelas': include 'pages/search_kelas.php';
	break;
	case 'data_jurusan': include 'pages/data_jurusan.php';
	break;
	case 'add_jurusan': include 'pages/add_jurusan.php';
	break;
	case 'edit_jurusan': include 'pages/edit_jurusan.php';
	break;
	case 'search_jurusan': include 'pages/search_jurusan.php';
	break;
	case 'data_dudi': include 'pages/data_dudi.php';
	break;
	case 'data_dudi_perjurusan': include 'pages/data_dudi_perjurusan.php';
	break;
	case 'add_dudi': include 'pages/add_dudi.php';
	break;
	case 'edit_dudi': include 'pages/edit_dudi.php';
	break;
	case 'search_dudi': include 'pages/search_dudi.php';
	break;
	case 'detail_dudi': include 'pages/detail_dudi.php';
	break;
	case 'data_guru': include 'pages/data_guru.php';
	break;
	case 'add_guru': include 'pages/add_guru.php';
	break;
	case 'edit_guru': include 'pages/edit_guru.php';
	break;
	case 'search_guru': include 'pages/search_guru.php';
	break;
	case 'detail_guru': include 'pages/detail_guru.php';
	break;
	case 'data_siswa': include 'pages/data_siswa.php';
	break;
	case 'data_siswa_perkelas': include 'pages/data_siswa_perkelas.php';
	break;
	case 'add_siswa': include 'pages/add_siswa.php';
	break;
	case 'edit_siswa': include 'pages/edit_siswa.php';
	break;
	case 'search_siswa': include 'pages/search_siswa.php';
	break;
	case 'detail_siswa': include 'pages/detail_siswa.php';
	break;
	case 'data_periode': include 'pages/data_periode.php';
	break;
	case 'add_periode': include 'pages/add_periode.php';
	break;
	case 'edit_periode': include 'pages/edit_periode.php';
	break;
	case 'search_periode': include 'pages/search_periode.php';
	break;
	case 'data_pembimbing': include 'pages/data_pembimbing.php';
	break;
	case 'add_pembimbing': include 'pages/add_pembimbing.php';
	break;
	case 'edit_pembimbing': include 'pages/edit_pembimbing.php';
	break;
	case 'search_pembimbing': include 'pages/search_pembimbing.php';
	break;
	case 'data_penempatan': include 'pages/data_penempatan.php';
	break;
	case 'add_penempatan': include 'pages/add_penempatan.php';
	break;
	case 'edit_penempatan': include 'pages/edit_penempatan.php';
	break;
	case 'search_penempatan': include 'pages/search_penempatan.php';
	break;
	case 'data_jurnal': include 'pages/data_jurnal.php';
	break;
	case 'add_jurnal': include 'pages/add_jurnal.php';
	break;
	case 'edit_jurnal': include 'pages/edit_jurnal.php';
	break;
	case 'search_jurnal': include 'pages/search_jurnal.php';
	break;
	case 'data_monitoring': include 'pages/data_monitoring.php';
	break;
	case 'add_monitoring': include 'pages/add_monitoring.php';
	break;
	case 'edit_monitoring': include 'pages/edit_monitoring.php';
	break;
	case 'search_monitoring': include 'pages/search_monitoring.php';
	break;
	case 'data_absensi': include 'pages/data_absensi.php';
	break;
	case 'add_absensi': include 'pages/add_absensi.php';
	break;
	case 'edit_absensi': include 'pages/edit_absensi.php';
	break;
	case 'search_absensi': include 'pages/search_absensi.php';
	break;
	case 'polling_line': include 'pages/polling_line.php';
	break;
	case 'polling': include 'inc/exec_polling.php';
	break;
	case 'dashboard': include 'user/dashboard.php';
	break;
	case 'profil_saya': include 'user/lihat_profil.php';
	break;
	case 'setting_profil': include 'user/setting_profil.php';
	break;
	case 'ganti_password': include 'user/ganti_password.php';
	break;
	case 'ganti_foto': include 'user/ganti_foto.php';
	break;
	case 'data_user': include 'user/data_user.php';
	break;
	case 'add_user': include 'user/add_user.php';
	break;
	case 'edit_user': include 'user/edit_user.php';
	break;
	case 'search_user': include 'user/search_user.php';
	break;
	case 'data_kategori': include 'user/data_kategori.php';
	break;
	case 'add_kategori': include 'user/add_kategori.php';
	break;
	case 'edit_kategori': include 'user/edit_kategori.php';
	break;
	case 'search_kategori': include 'user/search_kategori.php';
	break;
	case 'data_post': include 'user/data_post.php';
	break;
	case 'add_post': include 'user/add_post.php';
	break;
	case 'edit_post': include 'user/edit_post.php';
	break;
	case 'search_post': include 'user/search_post.php';
	break;
	case 'full_post': include 'pages/full_post.php';
	break;
	case 'search_main': include 'inc/search_main.php';
	break;
	case 'index': default:
?>		

	<div align="left" style="float: left; margin: 10px 0 0 10px; position: relative; display: inline;">
	<?php include 'nivo_slider.php'; ?>
	
	<!-- post content block -->
	<div id="post">
	<?php include 'inc/main.php'; ?>
	</div>
	</div>
	
<?php
	}
?>