<?php
	$page=(isset($_GET['page']))? $_GET['page']: "index";
	$txt="Sistem Informasi Prakerin";
	switch ($page) {
		case 'bkk': echo $txt." | BKK";
		break;
		case 'developer': echo $txt." | Developer";
		break;
		case 'gallery': echo $txt." | Gallery";
		break;
		case 'login': echo $txt." | Login";
		break;
		case 'prestasi': echo $txt." | Prestasi Sekolah";
		break;
		case 'profil': echo $txt." | Profil Sekolah";
		break;
		case 'titl': echo $txt." | Teknik Instalasi Tenaga Listrik";
		break;
		case 'tkr': echo $txt." | Teknik Kendaraan Ringan";
		break;
		case 'pbo': echo $txt." | Teknik Perbaikan Bodi Otomotif";
		break;
		case 'tp': echo $txt." | Teknik Pemesinan";
		break;
		case 'rpl': echo $txt." | Teknik Rekayasa Perangkat Lunak";
		break;
		case 'factory': echo $txt." | Teaching Factory";
		break;
		case 'data_dudi': echo $txt." | List Data Perusahaan (DU/DI)";
		break;
		case 'data_siswa': echo $txt." | List Data Siswa";
		break;
		case 'data_periode': echo $txt." | List Data Periode";
		break;
		case 'add_periode': echo $txt." | Tambah Periode";
		break;
		case 'edit_periode': echo $txt." | Edit Periode";
		break;
		case 'data_pembimbing': echo $txt." | List Data Pembimbing";
		break;
		case 'polling_line': echo $txt." | Polling Line";
		break;
		case 'admin': echo $txt." | Panel Admin";
		break;
		case 'data_post': echo $txt." | List Data Postingan";
		break;
		case 'add_post': echo $txt." | Tambah Postingan Baru";
		break;
		case 'edit_post': echo $txt." | Edit Postingan";
		break;
		case 'profil_saya': echo $txt." | Profil Saya";
		break;
		case 'setting_profil': echo $txt." | Setting Profil";
		break;
		case 'ganti_password': echo $txt." | Ganti Password";
		break;
		case 'ganti_foto': echo $txt." | Ganti Foto";
		break;
		case 'data_user': echo $txt." | List Data User";
		break;
		case 'index': default: echo $txt." | SMK Muhammadiyah Pekalongan";
	}
?>